/* Generated by scripts/generate_record_counts.py; do not edit manually. */
window.SOF_RECORD_COUNTS = Object.freeze({
  "IAF_1973_Losses.csv": 108,
  "NSSC - Terrorist attacks in Isr-Grid view.csv": 3198,
  "NSSC_Codebook.csv": 44,
  "NSSC_Terrorism_Israel_1948-2005.csv": 3198,
  "UNITS-Grid view.csv": 167,
  "UNITSLongevityN_90.csv": 90,
  "UNITSN_194.csv": 193,
  "Units Glossary-Grid.csv": 193,
  "Units_March_20262.csv": 229,
  "Units_March_2026_1_all.csv": 229,
  "attrition_operations.csv": 72,
  "individuals_global.csv": 49,
  "individuals_glossary.csv": 87,
  "palyam_operations1939-1948.csv": 26,
  "prestate_units.csv": 36,
  "regional_defensive.csv": 35,
  "reprisals.csv": 78,
  "sayeret_matkal_birds.csv": 7
});
