#!/usr/bin/env python3
"""Generate deterministic logical-row counts for the archive's CSV files."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
JSON_TARGET = ROOT / "record-counts.json"
JS_TARGET = ROOT / "js" / "record-counts.js"


def logical_record_count(path: Path) -> int:
    """Count non-empty CSV records after the header, respecting quoted newlines."""
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = csv.reader(handle)
        next(rows, None)
        return sum(1 for row in rows if any(cell.strip() for cell in row))


def collect_counts() -> dict[str, int]:
    return {
        path.name: logical_record_count(path)
        for path in sorted(ROOT.glob("*.csv"), key=lambda item: item.name.casefold())
    }


def render_json(counts: dict[str, int]) -> str:
    return json.dumps(counts, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def render_js(counts: dict[str, int]) -> str:
    payload = json.dumps(counts, ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "/* Generated by scripts/generate_record_counts.py; do not edit manually. */\n"
        f"window.SOF_RECORD_COUNTS = Object.freeze({payload});\n"
    )


def check_target(path: Path, expected: str) -> bool:
    return path.is_file() and path.read_text(encoding="utf-8") == expected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated files are absent or stale.",
    )
    args = parser.parse_args()

    counts = collect_counts()
    outputs = {
        JSON_TARGET: render_json(counts),
        JS_TARGET: render_js(counts),
    }

    if args.check:
        stale = [path.relative_to(ROOT) for path, text in outputs.items() if not check_target(path, text)]
        if stale:
            print("Generated record counts are stale:")
            for path in stale:
                print(f"  - {path}")
            print("Run: python3 scripts/generate_record_counts.py")
            return 1
        print(f"Record counts current for {len(counts)} CSV files.")
        return 0

    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
